### ISSUE TITLE
1. Valg af størrelse ved print af tavle (browserfunktion)

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#104]
2,54 x 2,54 cm
3 x 3 cm
5 x 5 cm
5,7 x 5,7 cm
8,9 x 8,9 cm
10 x 10 cm
15 x 15 cm
10,5 × 14,8 cm
6 x 9
8,3 x 11,3

**Comment by michaelkrog** [comment]
Omregning af mål:
2,54cm = 25,4mm = 72pt
3,0cm = 30,0mm = 85pt
5,0cm = 50mm = 142pt
5,7cm = 57mm = 162pt
6,0cm = 60mm = 170pt
8,3cm = 83mm = 235pt
8,9cm = 89mm = 252pt
9,0cm = 90mm = 255pt
10,0cm = 100mm = 283pt
10,5cm = 105mm = 298pt
11,3cm = 113mm = 320pt
14,8cm = 148mm = 420pt
15,0cm = 150mm = 425pt
