### ISSUE TITLE
Kan ikke slette eller redigere en oprettet post i kalenderen!

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#106]

**Comment by michaelkrog** [comment]
Det skyldes performance problemer med eventsystemet. Det der sker er at efter der er kommet meget data i databasen, så tager det lang tid at hente et helt event ud med alle data. Det tager faktisk så lang tid at browseren timer ud efter 60 sekunder og browseren modtager aldrig det fulde event objekt.

Samtidig visualiseres det ikke i brugerfalden at der loades og det opleves derfor som om at man blot ikke kan redigere eller slette data – men det skyldes i virkeligheden at der endnu ikke er modtaget data til redigering.

**Comment by michaelkrog** [comment]
....og dog. Det var vist en bøvs i mysqlserveren.

Efter at have masseret lidt, så kommer data retur efter 60 millisekunder.

**Comment by michaelkrog** [comment]
Det ER performanceissues relateret til events. Har forenklet datamodellen lidt, hvilket ser ud til at hjælpe.

**Comment by henrikravn** [comment]
fino...mindes at det var et stort problem i de kalenderposter der var konverteret.
