### ISSUE TITLE
Kan ikke sætte billede på relationer og hovedperson?

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#111]

**Comment by michaelkrog** [comment]
Det er korrekt. Det er pt. kun fra en mobil app man kan det. Det tjekker om der er et kamera tilgængeligt – hvis ikke gør den ingenting.

Men du vil gerne have upload personbilleder fra browser, ik?

**Comment by henrikravn** [comment]
jo
