### ISSUE TITLE
ville du overføre allerede eksisterende "grafik fra systemet" til ny version?

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#114]
Så vi efterfølgende blot skal fylder mere i via ftp?

**Comment by michaelkrog** [comment]
Jep. Det er et udestående i konverteringsscriptet, men det tilføjer jeg.

**Comment by henrikravn** [comment]
Super

**Comment by michaelkrog** [comment]
Konverteringsscriptet er fikset. Jeg konverterer data ved næste upload af ny version.
