### ISSUE TITLE
17:15:00.000 tid på post ved oprettelse eller redigering

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#115]
Der står 17:15:00.000 når der skal sættes tid eller redigeres tid på en post (mener det har været rettet)

**Comment by michaelkrog** [comment]
Er der et bestemt login hvormed jeg kan se dette reproduceret?

**Comment by henrikravn** [comment]
F.eks. Will på site.symbolkommunikation.dk firefox

**Comment by michaelkrog** [comment]
Ok. 

Firefox har ikke indbygget support for tidsvælgere:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#Browser_compatibility

**Comment by henrikravn** [comment]
ok, no problem
