### ISSUE TITLE
prøver at lave en tavle med et billede fra iPad'ens galleri

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#119]
...men kan ikke gemme tavlen.

**Comment by michaelkrog** [comment]
Kan der have været problemer med internetforbindelsen?

Jeg har prøvet selv med app'en(2.0.10) og det virker fint på min ipad.

**Comment by henrikravn** [comment]
Har lige sendt et billede ...kan godt oprette tavle nu...men den lægger et lag ovenpå som du kan se?

**Comment by michaelkrog** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/681472/6574780/76ef8160-c728-11e4-8aa4-c5f35af58a4b.jpg)

**Comment by michaelkrog** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/681472/6574807/bb9e3bc6-c728-11e4-8dc5-dfeddaab3427.jpg)

**Comment by michaelkrog** [comment]
Lukker denne. Har oprettet ny med det nye issue: https://github.com/henrikravn/symbol-mobile/issues/120
