### ISSUE TITLE
1. En bruger der har brugernavn med 4 cifre kan ikke logge ind

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#124]
Jeg har i admin-mode forsøgt at rette kodeord...men får følgende fejl: Username is invalid.
(Eks. 2306)

**Comment by michaelkrog** [comment]
Jeg har tilrettet alle brugernavn på mindre end 5 karakterer til at være 5 karakterer ved at udfylde med underscore.

john -> john_ (1 underscore tilføjet)
tj -> tj___ (3 underscores tlføjet)
ann -> ann__ (2 underscores tilføjet)

**Comment by michaelkrog** [comment]
Ahh. Okay.  Der er også en fejl i brugernavns-feltet i adminbrugerfladen. 

ng-pattern er /[a-zA-Z0-9]{5}/. Det skulle være være noget mere ala ([\w]{5,})
