### ISSUE TITLE
2. Der kan ikke oprettes tavler på nogle platforme - 2 problemer

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#125]
Efter jeg har valgt grafik fra "symbolkommunikation arkiv" eller "galleri" og skrives tekst osv. klikker/trykker jeg på "OK" for at gemme, men der sker intet.

Vælges der grafik fra computer loades billedet det ikke.
Billede fra kamera loades billedet ikke.

**Comment by michaelkrog** [comment]
Det skulle gerne være fikset nu. Det skyldtes filrettigheder der skulle justeres til efter datakonvertering.
