### ISSUE TITLE
3. ved oprettelse af relation

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#126]
1. Modtager jeg ingen velkomst mail
2. På app kan jeg ikke vælge mellem alle lande (der kan vælges dk el. uk) - det kan jeg kun på web version
3. Og hvis jeg rediger brugeren efter oprettelse (for ex. at indsætte et billede) får jeg først en besked om at der skal skrives kodeord (selvom jeg tidligere har gjort det) og når jeg så skriver det igen får jeg følgende besked:
Unable to persist user: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by michaelkrog** [comment]
1. Skulle virke nu efter konfig af mail er ændret.
2. App er ikke nyeste version. Den afventer hos apple.

**Comment by henrikravn** [comment]
3. ?

**Comment by michaelkrog** [comment]
Virker det ikke? 
Jeg har lige prøvet at oprette en og der fik jeg en mail.

**Comment by henrikravn** [comment]
ahh...der skulle stå 3. - sorry

**Comment by michaelkrog** [comment]
Ok. Jeg har ikke kigget på 3. endnu.
