### ISSUE TITLE
6. logo i top af login side (app og web) istedet for top tekst Symbolkommunikation

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#128]
![symbolkommunikation-logo](https://cloud.githubusercontent.com/assets/4361929/6728661/a1dd68a6-ce2b-11e4-8602-b05828e4ea3e.png)

PS:
Linktekst til Google plus i bunden mangler + så der står Google+

**Comment by henrikravn** [comment]
Logo tilpasser sig skærm, ik?

**Comment by michaelkrog** [comment]
Det kan godt tilpasses skærm. Men hvis det ikke skal være gnidret at se på i nogle tilfælde, så skal jeg bruge det i SVG-format.

**Comment by henrikravn** [comment]
Har sendt et nyt i svg
