### ISSUE TITLE
Opret relationer på app Android Fejl

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#58]
Når jeg ønsker at oprette en ny relation, udfylder jeg Fornavn, efternavn, telefon, e-mail, vælger land*, Relation, Vælger vis som kontakt, giver rettigheder, skriver brugernavn og kodeord og trykker til sidst på OK.
Resultatet er et skærmbillede med mørk bjælke i toppen hvor der står: <Tilbage  Relationer  Rediger
Nedenunder står der GENERAL.RELATIONS.
og under dette står der: 
Rettigheder
Admin, ChartEditor
Brugernavn 

Ekstra spørgsmål:
*Kommer der automatisk SE, NO og DE når de nye tekst filer uploades?
Hvor jeg kan indsætte billede, står der "Rediger" - måske bedre med "Foto"?

**Comment by michaelkrog** [comment]
> *Kommer der automatisk SE, NO og DE når de nye tekst filer uploades?
Nej, det kræver et par få liniers tilføjelse i koden og upload af app'en påny.

> Hvor jeg kan indsætte billede, står der "Rediger" - måske bedre med "Foto"?
Det kan ændres direkte i sprogfilerne. Se fx. https://github.com/henrikravn/symbol-mobile/blob/2.0/www/i18n/locale-da.json#L278. Der kan '@:GENERAL.EDIT' erstattes med fx. Foto.

**Comment by michaelkrog** [comment]
Fixed
