### ISSUE TITLE
Alarm på App og notifikationer Android

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#59]
Der er ikke alarm (Lyd) på hverken app eller notifikationer.

**Comment by michaelkrog** [comment]
Har fikset lyden i appen, men ikke på notifikationerne.

Har brugt en del tid på det nu, men kan ikke få det til at lykkes.
Notifikationerne ligger uden for det oprindelige scope for estimatet, så jeg lader det ligge indtil videre.
