### ISSUE TITLE
Sort fejl grafik i højre hjørne af app

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#61]

**Comment by michaelkrog** [comment]
Hvilken Android version er det?

**Comment by michaelkrog** [comment]
Har genskabt det i emulatoren nu.

Har oprettet et sprøgsmål om det hos Ionic da det ser ud til at være en fejl i Ionic:
http://forum.ionicframework.com/t/black-box-under-navbar-on-android/15102
