### ISSUE TITLE
Support siden

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#62]
I sort bjælke i toppen står der Support...men mangler Menu.
Der står Kontakt Support i blå kasse - ikke nødvendigt vel?
Telefon, mail er ikke aktiv når der trykkes?
Links åbner ligesom i app'en - hvilket gør det umuligt at komme tilbage. Bør vel åbne i nyt vindue, ik?

**Comment by michaelkrog** [comment]
Den blå kasse er en knap der åbner en forudfyldt mail. 

Den udfylder f.eks.:
```
Brugernavn: <navn>
Telefon: <telefon>
Email: <email>
Institution:
Kommentar:
```

**Comment by henrikravn** [comment]
Verdensklasse…så skal den bare være den rigtige blå :-)
Der skete ikke noget da jeg trykkede på den?

**Comment by michaelkrog** [comment]
Det er samme problem som telefon og mail nedenunder som ikke er aktive. Der er noget der skal aktiveres før mail- og telefon-links virker i app'en – det driller bare lige lidt. :)

**Comment by henrikravn** [comment]
oki :-)
