### ISSUE TITLE
Tekster og links til bunden af Symbolkommunikation

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#64]
DK: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-da.json)
Om Symbolkommunikation (link til http://positiverne.dk/symbol/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - struktur til mennesker med ADHD, Autisme, Aspergers syndrom og andre kognitive udfordringer.

EN: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-en.json)
About Symbolkommunikation (link til http://positiverne.dk/symboluk/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - Provides structure for people with ADHD, Autism, Asperger syndrome and other cognitive challenges.

DE: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-de.json)
Über Symbolkommunikation (link til http://positiverne.dk/symboluk/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - Struktur für Menschen mit ADHS, Autismus, Asperger-Syndrom und anderen kognitiven behinderungen.

SE: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-se.json)
Om Symbolkommunikation (link til http://positiverne.dk/symbol/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - struktur för personer med ADHD, autism, Aspergers syndrom och andra kognitiva utmaningar.

NO: (banner: http://www.positiverne.dk/symbol/try-free-symbol/banner-no.json)
Om Symbolkommunikation (link til http://positiverne.dk/symbol/)

Facebook (link til https://www.facebook.com/symbolkommunikation) 
Google+ (link til https://plus.google.com/116499944048175729358/posts)

©  Symbolkommunikation - struktur for personer med ADHD, autisme, Asperger syndrom og andre kognitive utfordringer.

**Comment by henrikravn** [comment]
Det forstår jeg simpelthen ikke...
Har lige uploadet dem igen efter de er lavet i Dreamw. og gemt som json filer.
Har du nogle idéer?

**Comment by michaelkrog** [comment]
Hej.

Nej, ikke umiddelbart.. Kender ikke jeres tekniske setup.
Har I ikke en webmaster der kan fikse det?

- Michael

**Comment by henrikravn** [comment]
hmm...jo, det er hende der har lavet dem i dreamw....havde selv lavet dem først i textwrangler.
Men jeg kan se at http://positiverne.dk/symbol/try-free-symbol/banner-da.json vises fint?
Jeg må finde ud af noget...
Anyway, har du da placeringen.

**Comment by michaelkrog** [comment]
Ok.

Den danske har stadig nogle ulovlige tegn(anførselstegnene).
I kan evt. validere dem med denne:
http://www.freeformatter.com/json-validator.html <http://www.freeformatter.com/json-validator.html>

Der kan i indtaste url’en, og så vil den vise om det er validt json format.

- Michael

**Comment by michaelkrog** [comment]
Fixed.

**Comment by henrikravn** [comment]
er dette rigtig kode?
{
    “image”: “<link til der hvor I har banneret liggende”,
    “link”: “<link hvortil banneret skal linke>”
}

**Comment by michaelkrog** [comment]
Hvis jeg validerer det med det link jeg sendte til dig(http://www.freeformatter.com/json-validator.html), så får jeg dette:
```
The JSON input is NOT valid according to RFC 4627 (JSON specification). Unexpected token “image” at position 10.
```

Så, nej det er ikke rigtig kode. Dette kan validere:
```
{
    "image": "http://www.positiverne.dk/symbol/try-free-symbol/DA.png",
    "link": "http://www.positiverne.dk/symbol/gratis-proeveperiode/"
}
```

**Comment by henrikravn** [comment]
Ok, så er det opklaret…jeg har jo kopieret det stykke kode du har sendt, ind i filerne.

Med venlig hilsen

Henrik Ravn

[cid:73AAFB98-618C-45F6-882D-C13956AA4C96]

9930 7583 | <her@exakt.dk> her<mailto:her@exakt.dk><mailto:lhk@exakt.dk><her@exakt.dk>@exakt.dk<mailto:her@exakt.dk>
Stenholm 7 | 9400 Nørresundby | 9819 3533 | exakt.dk<http://exakt.dk/shop/frontpage.html>

Find også Exakt på: Facebook<https://www.facebook.com/exaktdk> | LinkedIn<https://www.linkedin.com/company/exakt?trk=company_name> | Google+<https://plus.google.com/110183979779133868817/about> | Twitter<https://twitter.com/positiverne>

Se vores aktuelle aviser her<http://exakt.dk/shop/cms-23.html>

Fra: Michael Krog <notifications@github.com<mailto:notifications@github.com>>
Svar til: henrikravn/symbol-mobile <reply@reply.github.com<mailto:reply@reply.github.com>>
Dato: tirsdag den 6. januar 2015 12.24
Til: henrikravn/symbol-mobile <symbol-mobile@noreply.github.com<mailto:symbol-mobile@noreply.github.com>>
Cc: Henrik Ravn <her@exakt.dk<mailto:her@exakt.dk>>
Emne: Re: [symbol-mobile] Tekster og links til bunden af Symbolkommunikation (#64)


Hvis jeg validerer det med det link jeg sendte til dig(http://www.freeformatter.com/json-validator.html), så får jeg dette:

The JSON input is NOT valid according to RFC 4627 (JSON specification). Unexpected token “image” at position 10.


Så, nej det er ikke rigtig kode. Dette kan validere:

{
    "image": "http://www.positiverne.dk/symbol/try-free-symbol/DA.png",
    "link": "http://www.positiverne.dk/symbol/gratis-proeveperiode/"
}


—
Reply to this email directly or view it on GitHub<https://github.com/henrikravn/symbol-mobile/issues/64#issuecomment-68854459>.

________________________________
Denne mail er blevet scannet af http://www.comendo.com og indeholder ikke virus!
________________________________


********************************************************************************
Denne mail er blevet scannet af http://www.comendo.com og indeholder ikke virus!
********************************************************************************

**Comment by michaelkrog** [comment]
Ok.. Lad mig gætte.   I bruger outlook. :)
Den laver jævnt tit om på anførselstegn og den slags.

**Comment by henrikravn** [comment]
Jep…gider du indsætte det stykke kode i github?
Så retter jeg det til.
Med venlig hilsen

Henrik Ravn

[cid:951987C4-CC9E-4C27-953A-F3AD3D1410B5]

9930 7583 | <her@exakt.dk> her<mailto:her@exakt.dk><mailto:lhk@exakt.dk><her@exakt.dk>@exakt.dk<mailto:her@exakt.dk>
Stenholm 7 | 9400 Nørresundby | 9819 3533 | exakt.dk<http://exakt.dk/shop/frontpage.html>

Find også Exakt på: Facebook<https://www.facebook.com/exaktdk> | LinkedIn<https://www.linkedin.com/company/exakt?trk=company_name> | Google+<https://plus.google.com/110183979779133868817/about> | Twitter<https://twitter.com/positiverne>

Se vores aktuelle aviser her<http://exakt.dk/shop/cms-23.html>

Fra: Michael Krog <notifications@github.com<mailto:notifications@github.com>>
Svar til: henrikravn/symbol-mobile <reply@reply.github.com<mailto:reply@reply.github.com>>
Dato: tirsdag den 6. januar 2015 12.27
Til: henrikravn/symbol-mobile <symbol-mobile@noreply.github.com<mailto:symbol-mobile@noreply.github.com>>
Cc: Henrik Ravn <her@exakt.dk<mailto:her@exakt.dk>>
Emne: Re: [symbol-mobile] Tekster og links til bunden af Symbolkommunikation (#64)


Ok.. Lad mig gætte. I bruger outlook. :)
Den laver jævnt tit om på anførselstegn og den slags.

—
Reply to this email directly or view it on GitHub<https://github.com/henrikravn/symbol-mobile/issues/64#issuecomment-68854682>.

________________________________
Denne mail er blevet scannet af http://www.comendo.com og indeholder ikke virus!
________________________________


********************************************************************************
Denne mail er blevet scannet af http://www.comendo.com og indeholder ikke virus!
********************************************************************************

**Comment by michaelkrog** [comment]
Se issuet: https://github.com/henrikravn/symbol-mobile/issues/64

Det er deri jeg har skrevet det.

**Comment by henrikravn** [comment]
...så er de rettet til - tak!
( jeg hader outlook! )

**Comment by michaelkrog** [comment]
Så lidt. :)

Vi havde også meget "sjov" med Outlook hos Nykredit. :-(
