### ISSUE TITLE
listen af poster der vises under "rediger kalender"  

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#70]
...er alle med en tekst "ion-ios7-flag" under post titel og tidspunkt.
Ved en enkelt vises der et sort flag.

**Comment by michaelkrog** [comment]
Det lyder som en fejl i en tidligere version. 
Har du opdateret til sidste nye i testflight?

**Comment by henrikravn** [comment]
tjekker lige
