### ISSUE TITLE
Syntes ikke jeg kan finde (gem til print) knappen?

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#71]
...har jeg overset den?
Jeg kan se den på webversionen - men der mangler jeg at kunne vælge størrelse, f.eks. 5 cm. og 10 cm.?

**Comment by michaelkrog** [comment]
Den vises kun i en alm. browser. Ligesom i den gamle app er der ikke mulighed for at gemme pdf-filen lokalt med app'en og den ville blive åbnet på en måde så man ikke kan komme tilbage. 

Derfor har jeg skjult knappen.

**Comment by henrikravn** [comment]
Men selv på browser, kan jeg ikke vælge størrelse...hvilket er ret vigtigt?
Ville jeg ikke på app'en kunne downloade pdf'en til min enhed?

**Comment by michaelkrog** [comment]
Det med størrelsen er smuttet i forbi-farten. 

Mht. at downloade pdf'en til enheden, så kan den ikke det lige nu. Der er et API til at gemme billeder på enheden, men det er ikke sikkert det kan anvendes til PDF'er. Måske er det muligt, men jeg er ikke sikker.

Ingen af delene er noget jeg kan nå på den resterende tid.

**Comment by michaelkrog** [comment]
Der er vel egentlig 2 issues i denne tråd: 
1: Mangel på knap til download i app
2: Mangel på valg af størrelse.

Denne tråd handler om manglende knap. Hvis det andre skal løses må du gerne oprette et selvstændigt issue på det.

**Comment by henrikravn** [comment]
Ville det løse noget hvis vi i første omgang kun havde denne funktion på browser funktion?
At der kan hentes filer ned i 5x5 10x10 samt de badge størrelser vi havde tideliger?

**Comment by henrikravn** [comment]
...er løst ik?
