### ISSUE TITLE
1. Mulighed for indtastning af brugernavn og password til hovedperson mangler

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#75]

**Comment by henrikravn** [comment]
Er det uploadet?
Kan ikke se det...
![skaermbillede 2015-02-11 kl 11 40 22](https://cloud.githubusercontent.com/assets/4361929/6145515/d4c9f758-b1e2-11e4-8dbc-efefd577be7a.png)

**Comment by michaelkrog** [comment]
![skaermbillede 2015-03-10 kl 13 27 13](https://cloud.githubusercontent.com/assets/681472/6574850/384555f6-c729-11e4-8005-3c21c83c8880.png)
![skaermbillede 2015-03-10 kl 13 27 01](https://cloud.githubusercontent.com/assets/681472/6574849/3844f2e6-c729-11e4-8fbe-58d893356738.png)
