### ISSUE TITLE
3. Når de sidste sprog er lagt op, får jeg så flere muligheder når jeg vælger "Land"

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#76]
.... ved oprettelse af relationer og i admin oprettelse?
Nu er der DK og UK...men bør vel også indeholde DE, SE og NO - så det er de rigtige mails der sendes ud, eller?

**Comment by michaelkrog** [comment]
Jo. Det er en del af at de sidste sprog bliver lagt ind.
