### ISSUE TITLE
5. hvordan sletter jeg en bruger? fra admin modul og fra bruger panel?

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#78]
jeg har lige oprettet en "testfar" bruger...men kan ikke logge ind som denne bruger.
og ville slette, men kunne ikke finde ud af hvor?

Når jeg forsøger at logge ind, får jeg en besked boks med "Ingen Relationer"
Har også lige forsøgt med Ullaulla Ullaulla

**Comment by michaelkrog** [comment]
Har oprette ny issue til den del der har at gøre med log ind:
https://github.com/henrikravn/symbol-mobile/issues/105
