### ISSUE TITLE
ved ikke om webversion er opdateret...?

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#80]
1. kan ikke uploade Profilbillede 
2. når jeg vælger billede til tavler og vælger fra galleri er alle samlet et sted (der er jo oprettet kategorier til dette - de er med i oversættelsen) 
3. jeg har ingen mulighed for at fortryde og vælge en f.eks. fra computer, eller symbolkommunikation galleri
4. når jeg vil uploade et billede på 2 mb...logger den mig ud?
5. en tanke...det stor arkiv bliver også konverteret, ik - vil du fortælle mig hvilke mapper jeg derefter kan uploade ny symbolkommunikation grafik til?

**Comment by michaelkrog** [comment]
4. Jeg tror jeg sendte en mail om det på et tidspunkt. Jeg sender det lige igen.

**Comment by michaelkrog** [comment]
Hvis de ovenstående punkter skal løses, så må du gerne oprette dem som nye issues hver for sig.
