### ISSUE TITLE
1. Mangel på valg af størrelse ved download af tavle - som i symbolkommunikation v.1

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#81]
Mangel på valg af størrelse ved download af tavle - som i symbolkommunikation v.1
Undtagen A3 og A4 størrelse.
5x5 cm og 10x10 cm er absolut must!

**Comment by henrikravn** [comment]
Kan ikke se at denne er løst?

**Comment by michaelkrog** [comment]
Hvad er det der mangler? 
![skaermbillede 2015-03-03 kl 14 21 58](https://cloud.githubusercontent.com/assets/681472/6463235/b5577e80-c1b0-11e4-94cb-1cc41871f327.png)
