### ISSUE TITLE
"Opdater denne og følgende" sletter ikke de gamle poster

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#82]
@henrikravn skriver:
> Opdater denne og alle fremtidige - laver ekstra post / og nogle gange en helt ny postrække (se johnconner / johnconner profil)

**Comment by michaelkrog** [comment]
![skaermbillede 2015-01-18 kl 11 16 16](https://cloud.githubusercontent.com/assets/681472/5792038/755c1c20-9f03-11e4-9c48-7dfc55e1f280.png)

**Comment by michaelkrog** [comment]
Jeg kan ikke genskabe det lokalt. Måske der er en opdatering af serveren der er smuttet for mig.

Jeg har prøvet at ændre både tidspunkt for start samt interval for gentagelse, og det virker uden problemer. Der er inge dobbelte poster.  Jeg prøver at opdatere serveren og se om det blot er mig der har glemt at opdatere serveren med det sidste release.

**Comment by michaelkrog** [comment]
Kan ikke reproducere det. Hvis du kan så åbn denne igen.

**Comment by henrikravn** [comment]
det skete mange gange på messen - indtil jeg havde fået dem lært ikke at bruge denne knap :-)
I chrome browser.

**Comment by henrikravn** [comment]
hmm...har lige testet igen, uden at det opstår?
