### ISSUE TITLE
2. Mangler pinkode for log ud for hovedperson

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#86]
@henrikravn skriver:
> Kode på Logud for hovedperson

**Comment by henrikravn** [comment]
Er det fordi jeg skal rette tekst filer inden næste upload, at der vises en kodet tekst ud for dette?

**Comment by michaelkrog** [comment]
Hvor ser du den kodet tekst henne?

**Comment by henrikravn** [comment]
Ved at klikke på hovedperson og derefter rediger.
![skaermbillede 2015-02-11 kl 11 23 38](https://cloud.githubusercontent.com/assets/4361929/6145310/c3a1ff54-b1e0-11e4-9b4f-b799ed776ac6.png)
