### ISSUE TITLE
Bredere felt i ugevisningen

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#87]
@henrikravn skriver:
> Kan felt på ugevisning bliv bredere (som vil talte) - gør det lettere at se piktogram og tekst...måske bare 30-50% bredere (vurder  selv)

**Comment by michaelkrog** [comment]
Den skulle gerne allerede være det i app'en. Jeg havde ikke ændret noget i forhold til alm browser udgave, men jeg laver også den bredere.

**Comment by henrikravn** [comment]
ok, jeg er ikke sikker på jeg har den nyeste version på iPad...ved ikke lige hvordan jeg opdatere testapp'en?
