### ISSUE TITLE
9. Mangler intro grafik

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#89]
@henrikravn skriver:
> Mangler grafik paa forside

**Comment by michaelkrog** [comment]
Dette er pga. [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

Chrome skriver f.eks.: 
> XMLHttpRequest cannot load http://www.positiverne.dk/symbol/try-free-symbol/banner-da.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://site.symbolkommunikation.dk' is therefore not allowed access.

**Comment by henrikravn** [comment]
Så rykker vi den til sidst!
Fixer vi lige efter messen.

**Comment by henrikravn** [comment]
Hvad er hurtigst?

**Comment by michaelkrog** [comment]
Jo. Jeg flytter det til symbolkom serveren.
