### ISSUE TITLE
Kan ikke bladre til næste uge i uge kalender.

### ISSUE THREAD

**Issue by michaelkrog** [henrikravn/symbol-mobile#94]
@henrikravn skriver:
> Jeg kan ikke bladre til næste uge i uge kalender.

**Comment by michaelkrog** [comment]
Hvilken browser er det? Det fungerer fint i min chrome.
![skaermbillede 2015-01-19 kl 14 31 28](https://cloud.githubusercontent.com/assets/681472/5801131/e7c3a5f0-9fe7-11e4-9a9f-26f503f8a7ad.png)
![skaermbillede 2015-01-19 kl 14 31 36](https://cloud.githubusercontent.com/assets/681472/5801130/e7c2b7da-9fe7-11e4-9a96-aa80aa5f3172.png)

**Comment by henrikravn** [comment]
løst...ik?
