### ISSUE TITLE
1. vælg tavler til forløb

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#97]
Når der skal vælges tavler til forløb, er der en valg mulighed i toppen af det nye vindue...men valget har ingen indflydelse - alle tavler vises uanset.

**Comment by henrikravn** [comment]
Kan ikke se at denne er løst?

**Comment by michaelkrog** [comment]
Kan du forklare mig hvordan det kan genskabes. Har prøvet både med johnconner/johnconner og det ser ud til at virke fint.
