### ISSUE TITLE
2. tekst /sprog småting

### ISSUE THREAD

**Issue by henrikravn** [henrikravn/symbol-mobile#99]
Ved tidspunkt på post står der f.eks. 12.00 til 13.00. "til rettes til "-" (til er ikke med på sprogfil)
Slet knap skal tilknyttes sprogfil
Henrik: Jeg skal lige have rettet til "Save" i uk dok samt prosesser og forløb gøres ens.

**Comment by henrikravn** [comment]
09:00:00.000

**Comment by henrikravn** [comment]
Jeg har opdateret DA, DE, NO, SE, EN sprogfiler med tekst rettelser - vil du sørge for at de bliver opdateret i app og web udgave i Symbolkommunikation.

**Comment by henrikravn** [comment]
Kan kun vælge DK og UK i admin, når der skal oprettes ny bruger.

**Comment by michaelkrog** [comment]
Er det på site.symbolkommunikation.dk eller i app? Hvis jeg tjekker site.symbolkommunikation.dk har jeg DE, DK, NO, SV, UK

**Comment by henrikravn** [comment]
skønt...ret sikker på det ikke var der når jeg i admin mode ville oprette en ny bruger.
